CREATE TABLE `persons` (
	`Id` int(10) UNSIGNED NULL DEFAULT NULL,
	`FirstName` VARCHAR(50) NULL DEFAULT NULL,
	`LastName` VARCHAR(50) NULL DEFAULT NULL,
	`Adddres` VARCHAR(50) NULL DEFAULT NULL,
	`Gender` VARCHAR(50) NULL DEFAULT NULLpersons
)
ENGINE=InnoDB
;